# Site settings
title: 数据斯基
SEOTitle: 数据斯基
header-img: img/post-bg-miui6.jpg
email: rocky.28@qq.com
description: "数据分析 人人都会"
keyword: "博客, 个人网站, 互联网, 数据分析, 成长, Google Analytics, BigQuery, Similarweb, Excel, R语言"
url: "https://sjsj.life" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: true
# weibo_username: 
# zhihu_username: 
# github_username: 
# twitter_username: 
#facebook_username: 
#linkedin_username:  firstname-lastname-idxxxx

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: 

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: "G-FW18XWRL4Z" # Format: UA-xxxxxx-xx
ga_domain: sjsj.life

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "真理总沾着灰"
sidebar-avatar: https://avatars.githubusercontent.com/u/130053287?s=400 # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 5 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends:
  [
    { title: "百度", href: "http://baidu.com/" },
    { title: "必应", href: "http://cn.bing.com/" }
  ]

valine:
  enable: true # 设置为true，默认为false
  appid: Pjy6VEFTEmh84QaLV25sHh8B-gzGzoHsz  # 将应用key的App ID设置在这里
  appkey: xShhO8MeLS5XcoMy2ULtE7Wj # 将应用key的App Key设置在这里
  notify: true # 邮箱通知 , https://github.com/xCss/Valine/wiki，默认为false
  verify: false # 验证码 默认为false
  placeholder: Just go go ^_^ # 初始化评论显示，根据自己修改，这里默认，
  avatar: wavatar # 头像风格，默认为用不同面孔和背景组合生成的头像，可进入网址：https://valine.js.org/visitor.html查看头像设置，这里有许多头像风格，进行设置
  guest_info: nick, mail,link # 自定义评论标题
  pageSize: 10 # 分页大小，10页就自动分页
  visitor: true # 是否允许游客评论 ，进入官网查看设置：https://valine.js.org/visitor.html
